"use client";

import Image from "next/image";
import Link from "next/link";
import { Award, BookOpen, Briefcase, Check, Download, FileText, Globe2, GraduationCap, Heart, Languages, LockKeyhole, MapPin, Phone, Play, ShieldCheck, Sparkles, UserRound, UsersRound, Video } from "lucide-react";
import { useEffect, useState } from "react";
import { DashboardShell } from "@/components/dashboard-shell";
import { schoolNav } from "@/components/school-nav";
import { useToast } from "@/components/toast";

const UNLOCK_KEY="bulbeni.unlocked-teachers.v1";

export default function TeacherDetail(){
  const [saved,setSaved]=useState(false);const [unlocked,setUnlocked]=useState(false);const {showToast}=useToast();
  useEffect(()=>{const timer=window.setTimeout(()=>{try{setUnlocked(JSON.parse(localStorage.getItem(UNLOCK_KEY)||"[]").includes("emily-johnson"))}catch{}},0);return()=>clearTimeout(timer)},[]);
  const unlock=()=>{const current=JSON.parse(localStorage.getItem(UNLOCK_KEY)||"[]") as string[];if(!current.includes("emily-johnson"))localStorage.setItem(UNLOCK_KEY,JSON.stringify([...current,"emily-johnson"]));setUnlocked(true);showToast("Emily Johnson’s contact details and documents are now unlocked.")};
  return <DashboardShell nav={schoolNav} role="School" initials="AC" hideBottomSettings>
    <header className="teacher-detail-heading"><div><h1>Teacher Profile</h1><p>Review this teacher’s profile and unlock contact details to connect.</p></div><Link href="/school/teachers">← Back to teachers</Link></header>
    <section className="teacher-detail-hero"><div className="detail-avatar"><Image src="/Avatar%20.png" width={132} height={132} unoptimized alt="Emily Johnson"/></div><div className="detail-identity"><span className="detail-available">Available for opportunities</span><h2>Emily Johnson</h2><p><GraduationCap/> English Teacher <i/> <MapPin/> Ankara, Turkey</p><div className="detail-badges"><span><Briefcase/>8 years experience</span><span><Award/>CELTA</span><span><Languages/>English / Turkish</span><span><UsersRound/>Ages 11–18</span></div><div className="identity-extra"><span><Globe2/> British · Nationality</span><span><UserRound/> 32 years old</span></div></div><span className="detail-match"><strong>96%</strong>Match</span><div className="detail-actions"><button className={saved?"saved":""} onClick={()=>{setSaved(!saved);showToast(saved?"Teacher removed from saved list.":"Teacher saved successfully.")}}><Heart fill={saved?"currentColor":"none"}/>{saved?"Saved":"Save Teacher"}</button><button onClick={unlock} disabled={unlocked}><LockKeyhole/>{unlocked?"Contact Unlocked":"Unlock Contact Details"}</button></div></section>
    <div className="teacher-detail-layout"><main className="teacher-detail-main">
      <DetailCard icon={UserRound} title="About Me"><p className="detail-prose">I’m a passionate English teacher with eight years of experience helping students build confidence and achieve their language goals. My lessons are interactive, student-centred, and tailored to individual needs. I believe language learning opens doors to the world.</p></DetailCard>
      <DetailCard icon={Video} title="Introduction Video"><div className="detail-video"><Image src="/Avatar%20.png" width={560} height={250} unoptimized alt="Emily Johnson introduction video"/><button aria-label="Play introduction video"><Play fill="currentColor"/></button><div><Play fill="currentColor"/><span>0:00 / 1:28</span><i/><span>▣</span></div></div></DetailCard>
      <DetailCard icon={Briefcase} title="Teaching Experience"><div className="detail-timeline"><article><i/><span>2021 – Present</span><h3>English Teacher</h3><strong>ABC International School, Ankara</strong><small>Private High School · Ages 14–18</small><p>Teach English language and literature, prepare students for international examinations, and support cross-cultural projects.</p></article><article><i/><span>2017 – 2021</span><h3>English Language Teacher</h3><strong>Northbridge College, Istanbul</strong><small>International Middle School · Ages 11–14</small><p>Designed engaging lessons and supported curriculum planning across the English department.</p></article></div></DetailCard>
      <div className="teacher-detail-pair"><DetailCard icon={BookOpen} title="Subjects"><ul className="detail-check-list">{["English Language","English Literature","Exam Preparation","Academic Writing","Conversation & Fluency"].map(x=><li key={x}><Check/>{x}</li>)}</ul></DetailCard><DetailCard icon={UsersRound} title="Student Age Groups"><div className="detail-age-list"><span>Primary School <b>Ages 9–11</b></span><span>Middle School <b>Ages 11–14</b></span><span>High School <b>Ages 14–18</b></span></div></DetailCard></div>
      <DetailCard icon={GraduationCap} title="Education & Certificates"><div className="education-certificate-grid"><section><h3>Education</h3><article><span><GraduationCap/></span><div><strong>BA in English Language Teaching</strong><small>Hacettepe University · 2016</small></div></article><article><span><GraduationCap/></span><div><strong>MA in Applied Linguistics</strong><small>Ankara University · 2019</small></div></article></section><section><h3>Certificates</h3><article><span><Award/></span><div><strong>CELTA — Cambridge</strong><small>Issued 2019 · Document available <LockKeyhole/></small></div></article><article><span><Award/></span><div><strong>IELTS Teacher Training</strong><small>British Council · 2022</small></div></article></section></div><p className="verification-note"><ShieldCheck/> Certificate documents are pending BULBENI verification and remain locked before contact unlock.</p></DetailCard>
      <div className="teacher-detail-pair"><DetailCard icon={Languages} title="Languages"><dl className="detail-language-list"><div><dt>English</dt><dd>Native / Bilingual</dd></div><div><dt>Turkish</dt><dd>B2 · Upper intermediate</dd></div><div><dt>German</dt><dd>A2 · Basic</dd></div></dl></DetailCard><DetailCard icon={Sparkles} title="Teaching Preferences"><dl className="detail-preference-list"><div><dt>Teaching Mode</dt><dd>Online & In-person</dd></div><div><dt>Employment Type</dt><dd>Full-time / Part-time</dd></div><div><dt>Availability</dt><dd>Weekdays</dd></div><div><dt>Work Permit</dt><dd>Sponsorship required</dd></div><div><dt>Willing to Relocate</dt><dd>Yes</dd></div></dl></DetailCard></div>
    </main><aside className="teacher-detail-side">
      <DetailCard icon={Phone} title="Contact Information"><div className={`locked-contact ${unlocked?"unlocked":""}`}><ContactRow label="Email" value="emily.johnson@email.com" unlocked={unlocked}/><ContactRow label="Phone" value="+90 532 555 0174" unlocked={unlocked}/></div>{unlocked?<div className="unlock-success"><Check/> Contact Unlocked</div>:<><p className="unlock-copy"><LockKeyhole/> Unlock to view email and phone number.</p><button className="pay-unlock" onClick={unlock}>Pay to Unlock Contact Details</button></>}</DetailCard>
      <DetailCard icon={TargetIcon} title="Why recommended?"><p className="recommendation-copy">Emily is a strong match for ABC College based on:</p><ul className="recommendation-list">{["School type match","Student age group match","Languages of instruction match","English department alignment","High profile completeness"].map(x=><li key={x}><Check/>{x}</li>)}</ul></DetailCard>
      <DetailCard icon={FileText} title="Documents / CV"><div className="locked-documents"><Document name="Emily_Johnson_CV.pdf" unlocked={unlocked}/><Document name="CELTA_Certificate.pdf" unlocked={unlocked}/><Document name="English_Teaching_Diploma.pdf" unlocked={unlocked}/></div>{!unlocked&&<small className="document-lock-note"><LockKeyhole/> Files unlock with contact details</small>}</DetailCard>
    </aside></div>
  </DashboardShell>
}

function DetailCard({icon:Icon,title,children}:{icon:React.ComponentType<{size?:number}>;title:string;children:React.ReactNode}){return <section className="teacher-detail-card"><header><span><Icon/></span><h2>{title}</h2></header>{children}</section>}
function ContactRow({label,value,unlocked}:{label:string;value:string;unlocked:boolean}){return <div><span>{label}</span><strong className={unlocked?"":"blurred"}>{unlocked?value:"••••••••••••••••"}</strong>{!unlocked&&<LockKeyhole/>}</div>}
function Document({name,unlocked}:{name:string;unlocked:boolean}){return <div><span><FileText/><b>PDF</b></span><p><strong>{name}</strong><small>PDF Document · {unlocked?"Available":"Locked"}</small></p><button disabled={!unlocked} aria-label={`${unlocked?"Download":"Locked"} ${name}`}>{unlocked?<Download/>:<LockKeyhole/>}</button></div>}
function TargetIcon(){return <Sparkles/>}
