"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Award, BookOpen, Briefcase, CalendarDays, Check, ChevronRight, FileText, GraduationCap, Languages, MapPin, Save, School, Upload, UserRound, UsersRound, Video } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { teacherNav } from "@/components/teacher-nav";
import { useToast } from "@/components/toast";
import { completionSections, getProfileCompletion, initialTeacherProfile, isSectionComplete, TeacherProfile, useTeacherProfile } from "@/components/teacher-profile-store";
import { useI18n } from "@/components/i18n";

const sectionLinks = [
  ["profilePhoto","Profile photo",UserRound],["basic","Basic information",UserRound],["about","About me",BookOpen],["experience","Teaching experience",Briefcase],["education","Education",GraduationCap],["certificates","Certificates",Award],["subjects","Subjects",BookOpen],["ages","Student age groups",UsersRound],["languages","Languages",Languages],["schoolTypes","Previous school types",School],["workPreferences","Work preferences",CalendarDays],["cv","CV and documents",FileText],["video","Introduction video",Video],
] as const;

function Field({ label, value, onChange, placeholder, textarea=false }: { label:string; value:string; onChange:(value:string)=>void; placeholder?:string; textarea?:boolean }) {
  const {t}=useI18n();return <label className="form-field"><span>{t(label)}</span>{textarea ? <textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder?t(placeholder):undefined} rows={5}/> : <input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder?t(placeholder):undefined}/>}</label>;
}

export default function EditTeacherProfile() {
  const { profile, saveProfile, persistProfile, hydrated, loadError }=useTeacherProfile();
  const [form,setForm]=useState<TeacherProfile>(initialTeacherProfile); const {showToast}=useToast();
  const {t}=useI18n();
  const loaded=useRef(false);
  const saveBaseline=useRef<TeacherProfile>(initialTeacherProfile);
  useEffect(()=>{if(hydrated&&!loaded.current){setForm(profile);saveBaseline.current=profile;loaded.current=true}},[hydrated,profile]);
  useEffect(()=>{if(loaded.current)saveProfile(form)},[form,saveProfile]);
  const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  const addPhoto=(file?:File)=>{if(!file)return;if(file.size>450_000){showToast("Please choose a profile photo under 450 KB for this demo.");return}const reader=new FileReader();reader.onload=()=>{const next={...form,profilePhoto:String(reader.result)};setForm(next);showToast(`Profile photo added — your profile is now ${getProfileCompletion(next)}% complete.`)};reader.readAsDataURL(file)};
  const addEvidence=(file?:File)=>{if(!file)return;const next={...form,certificateEvidence:`${file.name}|${file.type}|${file.size}`};setForm(next);showToast(isSectionComplete(next,"certificates")?`Certificate evidence added — your profile is now ${getProfileCompletion(next)}% complete.`:"Evidence attached. Add the required certificate details to earn completion credit.")};
  const completed=useMemo(()=>completionSections.filter(section=>isSectionComplete(form,section.key)).length,[form]);
  const percentage=useMemo(()=>getProfileCompletion(form),[form]);
  const save=async()=>{const added=completionSections.filter(s=>!isSectionComplete(saveBaseline.current,s.key)&&isSectionComplete(form,s.key));let message=`Profile updated successfully — Your profile is now ${percentage}% complete.`;if(added.some(s=>s.key==="video"))message="Great! Adding an introduction video makes your profile stand out.";else if(added.some(s=>s.key==="experience"))message=`Teaching experience added — your profile is now ${percentage}% complete.`;else if(added.some(s=>s.key==="certificates"))message="Certificate added successfully.";try{await persistProfile(form);saveBaseline.current=form;showToast(message)}catch(cause){showToast(`Unable to update Supabase profile: ${cause instanceof Error?cause.message:"Unknown error"}`)}};
  return <DashboardShell nav={teacherNav} role="Teacher" initials="NS" hideBottomSettings>
    {loadError&&<div className="school-data-error">Unable to load Supabase profile: {loadError}</div>}
    <div className="edit-header"><div><Link href="/teacher/profile" className="back-link"><ArrowLeft/> {t("Back to profile")}</Link><h1>{t("Edit your profile")}</h1><p>{t("Tell schools what makes you a remarkable educator.")}</p></div><div className="edit-progress"><div><span>{t("Profile Completion")}</span><strong>{percentage}%</strong></div><i><b style={{width:`${percentage}%`}}/></i><small>{completed} / {sectionLinks.length}</small></div></div>
    <div className="edit-layout">
      <aside className="edit-nav panel"><span className="panel-kicker">{t("Profile sections")}</span>{sectionLinks.map(([key,label,Icon])=>{const done=isSectionComplete(form,key);return <a href={`#${key}`} key={key} className={done?"complete":""}><Icon size={16}/><span>{t(label)}</span>{done?<Check/>:<ChevronRight/>}</a>})}</aside>
      <form className="profile-form" onSubmit={e=>{e.preventDefault();save()}}>
        <FormSection id="profilePhoto" icon={UserRound} title="Profile photo" copy="A clear, professional portrait adds 10% to profile completion."><div className="photo-editor"><div className="photo-preview">{form.profilePhoto?<img src={form.profilePhoto} alt="Profile preview"/>:<span>{(form.firstName?.[0]||"M")+(form.lastName?.[0]||"A")}</span>}</div><div><label className="file-button">Upload or change photo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>addPhoto(e.target.files?.[0])}/></label><p>JPG, PNG or WebP · Maximum 450 KB for local demo storage.</p>{form.profilePhoto&&<button type="button" className="remove-file" onClick={()=>{set("profilePhoto","");showToast("Profile photo removed — completion has been updated.")}}>Remove photo</button>}</div></div></FormSection>
        <div className="form-section panel" id="basic"><div className="form-section-head"><span><UserRound/></span><div><h2>Basic information</h2><p>The essentials schools see first.</p></div></div><div className="form-grid"><Field label="First name" value={form.firstName} onChange={v=>set("firstName",v)}/><Field label="Last name" value={form.lastName} onChange={v=>set("lastName",v)}/><Field label="Professional title" value={form.subject} onChange={v=>set("subject",v)}/><Field label="Current location" value={form.location} onChange={v=>set("location",v)}/></div></div>
        <FormSection id="about" icon={BookOpen} title="About me" copy="Share your approach, values, and classroom personality."><Field label="Professional introduction" value={form.about} onChange={v=>set("about",v)} textarea/><span className="character-count">{form.about.length} / 600 characters</span></FormSection>
        <FormSection id="experience" icon={Briefcase} title="Teaching experience" copy="Summarize your most relevant roles."><Field label="Experience" value={form.experience} onChange={v=>set("experience",v)} textarea/><button type="button" className="add-row" onClick={()=>{set("experience",form.experience||"Primary Classroom Teacher — Add school and dates");showToast(`Teaching experience added — your profile is now ${getProfileCompletion({...form,experience:form.experience||"Primary Classroom Teacher — Add school and dates"})}% complete.`)}}>＋ Add another role</button></FormSection>
        <FormSection id="education" icon={GraduationCap} title="Education" copy="Add degrees and formal teacher training."><Field label="Degree and institution" value={form.education} onChange={v=>set("education",v)} /><button type="button" className="add-row">＋ Add education</button></FormSection>
        <FormSection id="certificates" icon={Award} title="Certificate evidence" copy="This section earns 10% only when required details and supporting evidence are present."><div className="form-grid"><Field label="Certificate name" value={form.certificates} onChange={v=>set("certificates",v)}/><Field label="Issuing organization" value={form.certificateIssuer} onChange={v=>set("certificateIssuer",v)}/><Field label="Issue date" value={form.certificateDate} onChange={v=>set("certificateDate",v)}/><Field label="Credential / reference number (optional)" value={form.certificateNumber} onChange={v=>set("certificateNumber",v)}/></div><label className="evidence-upload"><Upload/><span><strong>{form.certificateEvidence?.split("|")[0]||"Upload supporting evidence"}</strong><small>PDF, JPG or PNG · Demo stores file metadata only</small></span><input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>addEvidence(e.target.files?.[0])}/></label>{form.certificateEvidence&&<div className="pending-badge">Pending verification</div>}<p className="field-help">BULBENI does not verify documents in this prototype. Evidence is queued as pending only.</p></FormSection>
        <FormSection id="subjects" icon={BookOpen} title="Subjects" copy="Separate subjects with commas."><Field label="Subjects you teach" value={form.subjects} onChange={v=>set("subjects",v)}/></FormSection>
        <FormSection id="ages" icon={UsersRound} title="Student age groups" copy="Which learners do you have experience teaching?"><ChoiceRow choices={["Early years","Ages 6–8","Ages 9–11","Ages 12–14","Ages 15–18"]} value={form.ages} onChange={v=>set("ages",v)}/></FormSection>
        <FormSection id="languages" icon={Languages} title="Languages" copy="Include your proficiency for each language."><Field label="Languages and levels" value={form.languages} onChange={v=>set("languages",v)}/></FormSection>
        <FormSection id="schoolTypes" icon={School} title="Previous school types" copy="Help schools understand the environments you know."><ChoiceRow choices={["Public","Private","International","IB World","Montessori"]} value={form.schoolTypes} onChange={v=>set("schoolTypes",v)}/></FormSection>
        <FormSection id="video" icon={Video} title="Introduction video" copy="Worth 10% of profile completion—add a short link so schools can get to know you."><Field label="Video URL" value={form.video} onChange={v=>set("video",v)} placeholder="https://youtube.com/..."/><p className="field-help">A 60–90 second introduction works best. Only schools viewing your profile will see it.</p></FormSection>
        <FormSection id="cv" icon={FileText} title="CV and documents" copy="Upload a current CV and supporting documents."><div className="upload-box"><Upload/><strong>{form.cv || "Drop your CV here"}</strong><span>PDF or DOCX · Up to 10 MB</span><button type="button" onClick={()=>set("cv",form.cv?"":"Maya_Anderson_CV.pdf")}>{form.cv?"Remove file":"Choose file"}</button></div></FormSection>
        <FormSection id="workPreferences" icon={CalendarDays} title="Availability" copy="When could you begin a new role?"><Field label="Available from" value={form.availability} onChange={v=>set("availability",v)}/></FormSection>
        <FormSection id="employment" icon={Briefcase} title="Employment status" copy="Your current professional situation."><ChoiceRow choices={["Currently employed","Seeking work","Available immediately"]} value={form.employment} onChange={v=>set("employment",v)}/></FormSection>
        <FormSection id="relocation" icon={MapPin} title="Relocation preference" copy="Tell schools where you are open to working."><ChoiceRow choices={["Open to relocate within Europe","Open worldwide","Remote only","Not open to relocate"]} value={form.relocation} onChange={v=>set("relocation",v)}/></FormSection>
        <FormSection id="workPermit" icon={FileText} title="Work-permit status" copy="This helps schools understand hiring requirements."><ChoiceRow choices={["EU citizen","Valid local permit","Sponsorship required"]} value={form.workPermit} onChange={v=>set("workPermit",v)}/></FormSection>
        <div className="form-actions"><Link href="/teacher/profile" className="outline-button">{t("Cancel")}</Link><button className="primary-button" type="submit"><Save/> {t("Save profile")}</button></div>
      </form>
    </div>
  </DashboardShell>;
}

function FormSection({id,icon:Icon,title,copy,children}:{id:string;icon:React.ComponentType<{size?:number}>;title:string;copy:string;children:React.ReactNode}) { const {t}=useI18n();return <section className="form-section panel" id={id}><div className="form-section-head"><span><Icon/></span><div><h2>{t(title)}</h2><p>{t(copy)}</p></div></div>{children}</section> }
function ChoiceRow({choices,value,onChange}:{choices:string[];value:string;onChange:(v:string)=>void}) { const {value:translateValue}=useI18n();return <div className="choice-row">{choices.map(choice=><button type="button" key={choice} className={value.includes(choice)||value===choice?"selected":""} onClick={()=>onChange(choice)}>{(value.includes(choice)||value===choice)&&<Check/>}{translateValue(choice)}</button>)}</div> }
