"use client";

import Image from "next/image";
import Link from "next/link";
import { useParams } from "next/navigation";
import { Award, BookOpen, Briefcase, Check, Download, FileText, Globe2, GraduationCap, Heart, Languages, LockKeyhole, MapPin, Phone, ShieldCheck, Sparkles, UserRound, UsersRound, Video, X } from "lucide-react";
import { useEffect, useState } from "react";
import { DashboardShell } from "@/components/dashboard-shell";
import { schoolNav } from "@/components/school-nav";
import { useToast } from "@/components/toast";
import { getSupabaseClient } from "@/lib/supabase";
import { CONNECTION_REQUESTS_KEY, readTeacherIds, SAVED_TEACHERS_KEY, toggleTeacherId, writeTeacherIds } from "@/components/school-teacher-state";

type Teacher={id:string;full_name:string|null;subject:string|null;city:string|null;nationality:string|null;age:number|null;years_experience:number|null;languages:string[]|null;age_groups:string[]|null;certificates:string[]|null;education:string|null;school_type_experience:string[]|null;work_permit:string|null;willing_to_relocate:boolean|null;employment_type:string[]|null;teaching_mode:string[]|null;availability:string[]|null;has_video:boolean|null;has_cv:boolean|null;profile_image_url:string|null;email:string|null;phone:string|null;match_percentage:number|null;video_url:string|null;cv_url:string|null};
const list=(value:string[]|null|undefined)=>value??[];
const shown=(value:string|null|undefined)=>value||"Not provided";

export default function TeacherDetail(){
  const {id}=useParams<{id:string}>();const [teacher,setTeacher]=useState<Teacher|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [saved,setSaved]=useState(false);const [requestOpen,setRequestOpen]=useState(false);const [requested,setRequested]=useState(false);const [credits,setCredits]=useState(8);const {showToast}=useToast();
  useEffect(()=>{let active=true;(async()=>{try{const {data,error:queryError}=await getSupabaseClient().from("teachers").select("*").eq("id",id).single();if(queryError)throw queryError;if(active)setTeacher(data as Teacher);}catch(cause){if(active)setError(cause instanceof Error?cause.message:"Unable to load this teacher.");}finally{if(active)setLoading(false);}})();return()=>{active=false};},[id]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setRequested(readTeacherIds(CONNECTION_REQUESTS_KEY).includes(id));setSaved(readTeacherIds(SAVED_TEACHERS_KEY).includes(id))},0);return()=>clearTimeout(timer)},[id]);
  const submitRequest=()=>{const current=readTeacherIds(CONNECTION_REQUESTS_KEY);if(!current.includes(id))writeTeacherIds(CONNECTION_REQUESTS_KEY,[...current,id]);setCredits(value=>Math.max(0,value-1));setRequested(true);setRequestOpen(false);showToast("Request sent successfully.")};
  if(loading)return <DashboardShell nav={schoolNav} role="School" initials="AC" hideBottomSettings><header className="teacher-detail-heading"><div><h1>Teacher Profile</h1><p>Loading teacher profile...</p></div><Link href="/school/teachers">← Back to teachers</Link></header></DashboardShell>;
  if(error||!teacher)return <DashboardShell nav={schoolNav} role="School" initials="AC" hideBottomSettings><header className="teacher-detail-heading"><div><h1>Teacher Profile</h1><p>Unable to load teacher profile: {error||"Teacher not found."}</p></div><Link href="/school/teachers">← Back to teachers</Link></header></DashboardShell>;
  const name=teacher.full_name||"Teacher";const languages=list(teacher.languages);const ages=list(teacher.age_groups);const certificates=list(teacher.certificates);const schoolTypes=list(teacher.school_type_experience);
  return <DashboardShell nav={schoolNav} role="School" initials="AC" hideBottomSettings credits={credits}>
    <header className="teacher-detail-heading"><div><h1>Teacher Profile</h1><p>Review this teacher’s profile and unlock contact details to connect.</p></div><Link href="/school/teachers">← Back to teachers</Link></header>
    <section className="teacher-detail-hero"><div className="detail-avatar"><Image src={teacher.profile_image_url||"/Avatar%20.png"} width={132} height={132} unoptimized alt={name}/></div><div className="detail-identity"><span className="detail-available">{shown(list(teacher.availability)[0])}</span><h2>{name}</h2><p><GraduationCap/> {shown(teacher.subject)} <i/> <MapPin/> {shown(teacher.city)}</p><div className="detail-badges"><span><Briefcase/>{teacher.years_experience??0} years experience</span><span><Award/>{shown(certificates[0])}</span><span><Languages/>{languages.join(" / ")||"Not provided"}</span><span><UsersRound/>{ages.join(" / ")||"Not provided"}</span></div><div className="identity-extra"><span><Globe2/> {shown(teacher.nationality)} · Nationality</span><span><UserRound/> {teacher.age?`${teacher.age} years old`:"Age not provided"}</span></div></div><span className="detail-match"><strong>{teacher.match_percentage??0}%</strong>Match</span><div className="detail-actions"><button className={saved?"saved":""} onClick={()=>{const next=toggleTeacherId(SAVED_TEACHERS_KEY,id);const nowSaved=next.includes(id);setSaved(nowSaved);showToast(nowSaved?"Teacher saved successfully.":"Teacher removed from saved list.")}}><Heart fill={saved?"currentColor":"none"}/>{saved?"Saved":"Save Teacher"}</button><button onClick={()=>setRequestOpen(true)} disabled={requested}><LockKeyhole/>{requested?"Request Pending":"Request to Connect"}</button></div></section>
    <div className="teacher-detail-layout"><main className="teacher-detail-main">
      <DetailCard icon={UserRound} title="About Me"><p className="detail-prose">{name} is a {shown(teacher.subject).toLowerCase()} with {teacher.years_experience??0} years of teaching experience. Profile information shown here comes from the teacher’s BULBENI record.</p></DetailCard>
      <DetailCard icon={Video} title="Introduction Video">{teacher.has_video&&teacher.video_url?<div className="detail-video"><video src={teacher.video_url} controls preload="metadata" aria-label={`${name} introduction video`} style={{width:"100%",height:"100%",objectFit:"cover"}}/></div>:<p className="detail-prose">No introduction video is currently available.</p>}</DetailCard>
      <DetailCard icon={Briefcase} title="Teaching Experience"><div className="detail-timeline"><article><i/><span>{teacher.years_experience??0} years total experience</span><h3>{shown(teacher.subject)}</h3><strong>{schoolTypes.join(" · ")||"School type experience not provided"}</strong><small>{ages.join(" · ")||"Student age groups not provided"}</small></article></div></DetailCard>
      <div className="teacher-detail-pair"><DetailCard icon={BookOpen} title="Subjects"><ul className="detail-check-list"><li><Check/>{shown(teacher.subject)}</li></ul></DetailCard><DetailCard icon={UsersRound} title="Student Age Groups"><div className="detail-age-list">{ages.length?ages.map(x=><span key={x}>{x}</span>):<span>Not provided</span>}</div></DetailCard></div>
      <DetailCard icon={GraduationCap} title="Education & Certificates"><div className="education-certificate-grid"><section><h3>Education</h3><article><span><GraduationCap/></span><div><strong>{shown(teacher.education)}</strong></div></article></section><section><h3>Certificates</h3>{certificates.length?certificates.map(x=><article key={x}><span><Award/></span><div><strong>{x}</strong><small>Document remains locked <LockKeyhole/></small></div></article>):<article><div><strong>Not provided</strong></div></article>}</section></div><p className="verification-note"><ShieldCheck/> Certificate documents remain locked before contact unlock.</p></DetailCard>
      <div className="teacher-detail-pair"><DetailCard icon={Languages} title="Languages"><dl className="detail-language-list">{languages.length?languages.map(x=>{const [language,...level]=x.split(" - ");return <div key={x}><dt>{language}</dt><dd>{level.join(" - ")||"Listed"}</dd></div>}):<div><dt>Not provided</dt><dd>—</dd></div>}</dl></DetailCard><DetailCard icon={Sparkles} title="Teaching Preferences"><dl className="detail-preference-list"><Preference label="Teaching Mode" value={list(teacher.teaching_mode).join(" & ")}/><Preference label="Employment Type" value={list(teacher.employment_type).join(" / ")}/><Preference label="Availability" value={list(teacher.availability).join(" / ")}/><Preference label="Work Permit" value={teacher.work_permit}/><Preference label="Willing to Relocate" value={teacher.willing_to_relocate===null?"Not provided":teacher.willing_to_relocate?"Yes":"No"}/></dl></DetailCard></div>
    </main><aside className="teacher-detail-side">
      <DetailCard icon={Phone} title="Contact Information"><div className={`locked-contact ${requested?"unlocked":""}`}><ContactRow label="Email" value={shown(teacher.email)} unlocked={requested}/><ContactRow label="Phone" value={shown(teacher.phone)} unlocked={requested}/></div>{requested?<div className="connection-approved"><Check/> Connection Approved · Contact Unlocked</div>:<><p className="unlock-copy"><LockKeyhole/> Request a connection to view email and phone number.</p><button className="pay-unlock" onClick={()=>setRequestOpen(true)}>Request to Connect</button></>}</DetailCard>
      <DetailCard icon={TargetIcon} title="Why recommended?"><p className="recommendation-copy">{name} is a {teacher.match_percentage??0}% match based on the school and teacher profile data.</p><ul className="recommendation-list">{[teacher.subject,...ages,...languages].filter((x):x is string=>Boolean(x)).slice(0,5).map(x=><li key={x}><Check/>{x}</li>)}</ul></DetailCard>
      <DetailCard icon={FileText} title="Documents / CV"><div className="locked-documents"><Document name={`${name.replace(/\s+/g,"_")}_CV.pdf`} unlocked={requested} available={Boolean(teacher.has_cv&&teacher.cv_url)} url={teacher.cv_url}/></div>{!requested&&<small className="document-lock-note"><LockKeyhole/> Files unlock when the connection is approved</small>}</DetailCard>
    </aside></div>
    {requestOpen&&<div className="prototype-modal-layer" role="presentation" onMouseDown={()=>setRequestOpen(false)}><section className="prototype-modal" role="dialog" aria-modal="true" aria-labelledby="request-connect-title" onMouseDown={event=>event.stopPropagation()}><header><div><span>Teacher connection</span><h2 id="request-connect-title">Request to Connect</h2></div><button onClick={()=>setRequestOpen(false)} aria-label="Close"><X/></button></header><p>Connecting with this teacher will use 1 credit.</p><div className="modal-credit-balance"><span>Current balance</span><strong>{credits} Credits</strong></div><footer><button onClick={()=>setRequestOpen(false)}>Cancel</button><button onClick={submitRequest} disabled={credits<1}>Use 1 Credit</button></footer></section></div>}
  </DashboardShell>
}

function DetailCard({icon:Icon,title,children}:{icon:React.ComponentType<{size?:number}>;title:string;children:React.ReactNode}){return <section className="teacher-detail-card"><header><span><Icon/></span><h2>{title}</h2></header>{children}</section>}
function Preference({label,value}:{label:string;value:string|null|undefined}){return <div><dt>{label}</dt><dd>{value||"Not provided"}</dd></div>}
function ContactRow({label,value,unlocked}:{label:string;value:string;unlocked:boolean}){return <div><span>{label}</span><strong className={unlocked?"":"blurred"}>{unlocked?value:"••••••••••••••••"}</strong>{!unlocked&&<LockKeyhole/>}</div>}
function Document({name,unlocked,available,url}:{name:string;unlocked:boolean;available:boolean;url:string|null}){const canOpen=unlocked&&available&&Boolean(url);return <div><span><FileText/><b>PDF</b></span><p><strong>{available?name:"CV not provided"}</strong><small>PDF Document · {canOpen?"Available":unlocked?"Not provided":"Locked"}</small></p><button disabled={!canOpen} onClick={()=>{if(url)window.open(url,"_blank","noopener,noreferrer")}} aria-label={canOpen?`Open ${name}`:`${unlocked?"Unavailable":"Locked"} ${name}`}>{canOpen?<Download/>:<LockKeyhole/>}</button></div>}
function TargetIcon(){return <Sparkles/>}
