"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";

export type Language="en"|"tr";
const STORAGE_KEY="bulbeni.language.v1";
const tr:Record<string,string>={
  "How it works":"Nasıl çalışır","Why Bulbeni":"Neden Bulbeni?","Find your fit":"Eşleşmeni bul",
  "Dashboard":"Ana Sayfa","My Profile":"Profilim","Teachers":"Öğretmenler","Saved Teachers":"Kaydedilen Öğretmenler","Unlocked Contacts":"Açılan İletişimler","Schools":"Okullar","Settings":"Ayarlar","Workspace":"Çalışma Alanı","Back to home":"Ana sayfaya dön","Teacher account":"Öğretmen hesabı","School account":"Okul hesabı","Teacher workspace":"Öğretmen çalışma alanı","School workspace":"Okul çalışma alanı","Educator profile":"Eğitmen profili",
  "Credits":"Kredi","Buy Credits":"Kredi Satın Al","Prototype packages":"Prototip paketleri","Select a mock credit package. No payment will be processed.":"Bir demo kredi paketi seçin. Ödeme alınmayacaktır.","Demo package":"Demo paketi","Cancel":"İptal","Close":"Kapat",
  "Discover Teachers":"Öğretmenleri Keşfet","Browse matching teachers and save your favourites.":"Uygun öğretmenleri inceleyin ve favorilerinize kaydedin.","Recommended for You":"Size Önerilenler","Why these teachers?":"Neden bu öğretmenler?","All Teachers":"Tüm Öğretmenler","Recommended":"Önerilenler","Search teachers by name, subject, city...":"Öğretmen adı, branş veya şehir ara...","Subject":"Branş","City":"Şehir","Experience":"Deneyim","Age Group":"Yaş Grubu","Language":"Dil","Profile Completion":"Profil Tamamlama","Advanced Search":"Gelişmiş Arama","Clear Filters":"Filtreleri Temizle","Teacher filters":"Öğretmen filtreleri","Personal":"Kişisel","Professional":"Mesleki","Work / Employment":"İş / İstihdam","Profile Assets":"Profil İçerikleri","Gender":"Cinsiyet","Nationality":"Uyruk","Age":"Yaş","Education":"Eğitim","Certificates":"Sertifikalar","School Type Experience":"Okul Türü Deneyimi","Availability":"Müsaitlik","Work Permit":"Çalışma İzni","Willing to Relocate":"Taşınmaya Açık","Employment Type":"Çalışma Türü","Teaching Mode":"Eğitim Şekli","Has Video":"Videosu Var","Has CV":"CV'si Var","Any":"Tümü","Yes":"Evet","No":"Hayır","Apply Filters":"Filtreleri Uygula","No teachers match these filters":"Bu filtrelere uygun öğretmen bulunamadı","Clear or adjust your search and filters to see more teachers.":"Daha fazla öğretmen görmek için filtreleri temizleyin veya değiştirin.","Loading teachers...":"Öğretmenler yükleniyor...","teachers found":"öğretmen bulundu","View Profile":"Profili Görüntüle",
  "Teacher Profile":"Öğretmen Profili","Review this teacher’s profile and unlock contact details to connect.":"Öğretmenin profilini inceleyin ve iletişime geçmek için bilgilerini açın.","Back to teachers":"Öğretmenlere dön","Save Teacher":"Öğretmeni Kaydet","Saved":"Kaydedildi","Request to Connect":"Bağlantı Talebi Gönder","Request Pending":"Talep Beklemede","Teacher connection":"Öğretmen bağlantısı","Connecting with this teacher will use 1 credit.":"Bu öğretmenle bağlantı kurmak 1 kredi kullanır.","Current balance":"Mevcut bakiye","Use 1 Credit":"1 Kredi Kullan","Request sent successfully.":"Bağlantı talebi başarıyla gönderildi.","Contact Information":"İletişim Bilgileri","Email":"E-posta","Phone":"Telefon","Connection Approved":"Bağlantı Onaylandı","Contact Unlocked":"İletişim Açıldı","Documents / CV":"Belgeler / CV","Files unlock when the connection is approved":"Bağlantı onaylandığında dosyalar açılır","About Me":"Hakkımda","Introduction Video":"Tanıtım Videosu","Teaching Experience":"Öğretmenlik Deneyimi","Subjects":"Branşlar","Student Age Groups":"Öğrenci Yaş Grupları","Education & Certificates":"Eğitim ve Sertifikalar","Languages":"Diller","Teaching Preferences":"Eğitim Tercihleri","Why recommended?":"Neden önerildi?",
  "School dashboard":"Okul ana sayfası","Welcome back":"Tekrar hoş geldiniz","Discover matching teachers and manage your profile from one place.":"Uygun öğretmenleri keşfedin ve profilinizi tek yerden yönetin.","Teacher discovery":"Öğretmen keşfi","Find the right teachers for your school":"Okulunuz için doğru öğretmenleri bulun","Browse Teachers":"Öğretmenlere Göz At","Recommended Teachers":"Önerilen Öğretmenler","View all teachers":"Tüm öğretmenleri görüntüle","Quick Actions":"Hızlı İşlemler","Browse all teachers":"Tüm öğretmenlere göz at","Update school profile":"Okul profilini güncelle","Review saved teachers":"Kaydedilen öğretmenleri incele","View unlocked contacts":"Açılan iletişimleri görüntüle","Top Matches":"En İyi Eşleşmeler","See all":"Tümünü gör","Recently Viewed Teachers":"Son Görüntülenen Öğretmenler","Contacts Unlocked":"Açılan İletişimler",
  "Explore compatible educators based on your school type, curriculum, student ages, languages of instruction, and location.":"Okul türünüz, müfredatınız, öğrenci yaşları, eğitim dilleri ve konumunuza göre uygun eğitimcileri keşfedin.","School account statistics":"Okul hesabı istatistikleri","Available in the live directory":"Canlı dizinde mevcut","Tracking is not connected yet":"Takip henüz bağlı değil","Available in your contacts":"İletişimlerinizde mevcut","Ready to review":"İncelemeye hazır","Curated for":"Özel olarak seçildi:","Highest matches from the live teacher directory.":"Canlı öğretmen dizinindeki en yüksek eşleşmeler.","Recommendations use the information in your school profile:":"Öneriler okul profilinizdeki bilgileri kullanır:","Student age groups":"Öğrenci yaş grupları","Languages of instruction":"Eğitim dilleri","Subject alignment":"Branş uyumu","Profile details":"Profil bilgileri","Rule-based prototype recommendations":"Kural tabanlı prototip önerileri","Why this teacher matches":"Bu öğretmen neden eşleşiyor?","match":"eşleşme","years":"yıl","Age groups":"Yaş grupları","Not provided":"Belirtilmedi","Subject not provided":"Branş belirtilmedi","Location not provided":"Konum belirtilmedi","Remove":"Kaldır","Save":"Kaydet","saved for review.":"incelemek üzere kaydedildi.","removed from saved teachers.":"kaydedilen öğretmenlerden kaldırıldı.",
  "School Profile":"Okul Profili","Edit school profile":"Okul profilini düzenle","School profile":"Okul profili","Edit Profile":"Profili Düzenle","View Public Profile":"Herkese Açık Profili Gör","Profile sections":"Profil bölümleri","School logo":"Okul logosu","Basic information":"Temel bilgiler","Students & education":"Öğrenciler ve eğitim","School details":"Okul bilgileri","Teacher support":"Öğretmen desteği","Facilities & highlights":"Olanaklar ve öne çıkanlar","Contact information":"İletişim bilgileri","Save Changes":"Değişiklikleri Kaydet","About Our School":"Okulumuz Hakkında","Students & Education":"Öğrenciler ve Eğitim","Teacher Support":"Öğretmen Desteği","Facilities & Highlights":"Olanaklar ve Öne Çıkanlar","School at a Glance":"Kısaca Okul","Learning Community":"Öğrenme Topluluğu","Visit school website":"Okul web sitesini ziyaret et",
  "Good morning":"Günaydın","Your Profile":"Profiliniz","Profile strength":"Profil gücü","You’re making great progress":"Harika ilerliyorsunuz","Continue editing":"Düzenlemeye devam et","Profile views":"Profil görüntülenmeleri","Your next steps":"Sonraki adımlarınız","Profile checklist":"Profil kontrol listesi","Profile tip":"Profil ipucu","Add introduction video":"Tanıtım videosu ekle","Manage documents":"Belgeleri yönet","Edit your profile":"Profilinizi düzenleyin","Tell schools what makes you a remarkable educator.":"Sizi özel bir eğitimci yapan özellikleri okullarla paylaşın.","Back to profile":"Profile dön","Profile photo":"Profil fotoğrafı","About me":"Hakkımda","Previous school types":"Önceki okul türleri","Work preferences":"Çalışma tercihleri","CV and documents":"CV ve belgeler","Employment status":"Çalışma durumu","Relocation preference":"Taşınma tercihi","Work-permit status":"Çalışma izni durumu","Save profile":"Profili Kaydet","Discover Schools":"Okulları Keşfet","School directory":"Okul rehberi","Explore live school profiles that may match your teaching preferences.":"Eğitim tercihlerinize uygun olabilecek güncel okul profillerini keşfedin.","Search by name, city, or type...":"Ad, şehir veya türe göre ara...","Visit School Website":"Okul Web Sitesini Ziyaret Et","Website not provided":"Web sitesi belirtilmemiş",
  "Full-time":"Tam zamanlı","Part-time":"Yarı zamanlı","Online":"Çevrim içi","In-person":"Yüz yüze","Available":"Mevcut","Adults":"Yetişkinler","High School":"Lise","Middle School":"Ortaokul","Primary School":"İlkokul","University":"Üniversite","Weekdays":"Hafta içi","Evenings":"Akşamları","Immediately":"Hemen"
};
type I18n={language:Language;setLanguage:(language:Language)=>void;t:(key:string)=>string;value:(value:string)=>string};
const Context=createContext<I18n|null>(null);
export function I18nProvider({children}:{children:React.ReactNode}){const [language,setLanguageState]=useState<Language>("en");useEffect(()=>{const saved=localStorage.getItem(STORAGE_KEY);if(saved==="tr"||saved==="en")setLanguageState(saved)},[]);const setLanguage=useCallback((next:Language)=>{setLanguageState(next);localStorage.setItem(STORAGE_KEY,next);document.documentElement.lang=next},[]);const t=useCallback((key:string)=>language==="tr"?(tr[key]||key):key,[language]);const value=useCallback((input:string)=>language==="tr"?(tr[input]||input):input,[language]);const context=useMemo(()=>({language,setLanguage,t,value}),[language,setLanguage,t,value]);return <Context.Provider value={context}>{children}</Context.Provider>}
export function useI18n(){const value=useContext(Context);if(!value)throw new Error("useI18n must be used within I18nProvider");return value}
