import { getSupabaseClient } from "@/lib/supabase";
import type { TeacherProfile } from "@/components/teacher-profile-store";

export const DEMO_TEACHER_ID="09ad6480-d351-48af-bcbd-819a2e9ac994";
type TeacherRow={id:string;full_name:string|null;subject:string|null;city:string|null;nationality:string|null;age:number|null;years_experience:number|null;languages:string[]|null;age_groups:string[]|null;certificates:string[]|null;education:string|null;school_type_experience:string[]|null;work_permit:string|null;willing_to_relocate:boolean|null;employment_type:string[]|null;teaching_mode:string[]|null;availability:string[]|null;has_video:boolean|null;has_cv:boolean|null;profile_image_url:string|null;video_url:string|null;cv_url:string|null};
const names=(fullName:string|null)=>{const parts=(fullName||"").trim().split(/\s+/);return {firstName:parts.shift()||"",lastName:parts.join(" ")}};
export function teacherRowToProfile(row:TeacherRow):TeacherProfile{const name=names(row.full_name);return {...name,profilePhoto:row.profile_image_url||"",subject:row.subject||"",location:row.city||"",about:"",experience:row.years_experience?`${row.years_experience} years of teaching experience`:"",education:row.education||"",certificates:(row.certificates??[]).join("; "),certificateIssuer:"",certificateDate:"",certificateNumber:"",certificateEvidence:"",subjects:row.subject||"",ages:(row.age_groups??[]).join("|"),languages:(row.languages??[]).join("; "),schoolTypes:(row.school_type_experience??[]).join("|"),video:row.video_url||"",cv:row.has_cv?(row.cv_url||"CV available"):"",availability:(row.availability??[]).join("; "),employment:(row.employment_type??[]).join("|"),relocation:row.willing_to_relocate?"Open to relocate":"Not open to relocate",workPermit:row.work_permit||"",yearsExperience:String(row.years_experience??0),nationality:row.nationality||"",teachingMode:(row.teaching_mode??[]).join("|"),age:String(row.age??"")};}
export async function loadDemoTeacherProfile(){const {data,error}=await getSupabaseClient().from("teachers").select("*").eq("id",DEMO_TEACHER_ID).single();if(error)throw error;return teacherRowToProfile(data as TeacherRow)}
export async function saveDemoTeacherProfile(profile:TeacherProfile){const payload={full_name:`${profile.firstName} ${profile.lastName}`.trim(),subject:profile.subject,city:profile.location,languages:profile.languages.split(";").map(x=>x.trim()).filter(Boolean),age_groups:profile.ages.split("|").filter(Boolean),certificates:profile.certificates.split(";").map(x=>x.trim()).filter(Boolean),education:profile.education||null,school_type_experience:profile.schoolTypes.split("|").filter(Boolean),work_permit:profile.workPermit||null,willing_to_relocate:!profile.relocation.toLowerCase().startsWith("not "),employment_type:profile.employment.split("|").filter(Boolean),teaching_mode:profile.teachingMode?.split("|").filter(Boolean)??[],availability:profile.availability.split(";").map(x=>x.trim()).filter(Boolean),has_video:Boolean(profile.video),has_cv:Boolean(profile.cv),video_url:profile.video||null};const {data,error}=await getSupabaseClient().from("teachers").update(payload).eq("id",DEMO_TEACHER_ID).select("*").single();if(error)throw error;return teacherRowToProfile(data as TeacherRow)}
