"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Award, ChevronDown, Clock3, Heart, Languages, MapPin, RotateCcw, Search, SlidersHorizontal, Sparkles, Star, Target, UsersRound, X } from "lucide-react";
import { DashboardShell } from "@/components/dashboard-shell";
import { schoolNav } from "@/components/school-nav";
import { useToast } from "@/components/toast";
import { getSupabaseClient } from "@/lib/supabase";
import { readTeacherIds, SAVED_TEACHERS_KEY, toggleTeacherId } from "@/components/school-teacher-state";
import { DEMO_SCHOOL_ID } from "@/components/school-supabase-profile";

type TeacherRow={id:string;full_name:string|null;subject:string|null;city:string|null;nationality:string|null;age:number|null;years_experience:number|null;languages:string[]|null;age_groups:string[]|null;certificates:string[]|null;education:string|null;school_type_experience:string[]|null;work_permit:string|null;willing_to_relocate:boolean|null;employment_type:string[]|null;teaching_mode:string[]|null;availability:string[]|null;has_video:boolean|null;has_cv:boolean|null;profile_image_url:string|null};
type SchoolRow={name:string|null;city:string|null;school_type:string|null;age_groups:string[]|null;languages_of_instruction:string[]|null;subjects:string[]|null;work_permit_support:string|null};
type Teacher=TeacherRow&{name:string;match:number;years:number;languageDisplay:string;ageDisplay:string;certificateDisplay:string;tone:string;imageUrl:string;reasons:string[]};
const tones=["mint","blue","sand"];
const normalized=(value:string|null|undefined)=>value?.trim().toLowerCase()||"";
const unique=(values:string[])=>[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b));
const overlap=(left:string[],right:string[])=>left.some(a=>right.some(b=>normalized(a)===normalized(b)||normalized(a).includes(normalized(b))||normalized(b).includes(normalized(a))));
const languageName=(value:string)=>value.split(/\s+-\s+/)[0].trim();
const compatibleSchoolType=(schoolType:string,experience:string[])=>["private","international","public","language","ib","k-12"].some(token=>normalized(schoolType).includes(token)&&experience.some(item=>normalized(item).includes(token)));

function scoreTeacher(row:TeacherRow,school:SchoolRow|null){
  let score=0;const reasons:string[]=[];const schoolSubjects=school?.subjects??[];const schoolAges=school?.age_groups??[];const schoolLanguages=school?.languages_of_instruction??[];const teacherLanguages=(row.languages??[]).map(languageName);
  if(row.subject&&overlap([row.subject],schoolSubjects)){score+=30;reasons.push(`Matches your ${row.subject.replace(/ teacher/i,"")} department`)}
  if(overlap(row.age_groups??[],schoolAges)){score+=20;const age=(row.age_groups??[]).find(item=>overlap([item],schoolAges));if(age)reasons.push(`Experienced with ${age.toLowerCase()} students`)}
  if(school?.school_type&&compatibleSchoolType(school.school_type,row.school_type_experience??[])){score+=15;reasons.push(`Experienced in ${school.school_type.toLowerCase()} settings`)}
  if(overlap(teacherLanguages,schoolLanguages)){score+=10;const language=teacherLanguages.find(item=>overlap([item],schoolLanguages));if(language)reasons.push(`${language}-medium teaching experience`)}
  const permit=normalized(row.work_permit);const schoolSupports=normalized(school?.work_permit_support);if(permit&&(permit.includes("available")||permit.includes("not required")||permit.includes("eu")||permit.includes("valid")||schoolSupports.includes("yes"))){score+=10;reasons.push("Work permit compatible")}
  if(row.city&&school?.city&&normalized(row.city)===normalized(school.city)){score+=5;reasons.push(`Located in ${row.city}`)}
  score+=Math.min(5,Math.max(0,(row.years_experience??0)/2));
  if(row.has_cv)score+=3;if(row.has_video)score+=2;
  return {score:Math.round(Math.min(100,score)),reasons};
}

const advancedGroups=[
  {title:"Personal",fields:["Gender","Nationality","Age"]},
  {title:"Professional",fields:["Education","Certificates","School Type Experience"]},
  {title:"Work / Employment",fields:["Availability","Work Permit","Willing to Relocate","Employment Type","Teaching Mode"]},
  {title:"Profile Assets",fields:["Has Video","Has CV"]},
];

export default function DiscoverTeachers(){
  const [rows,setRows]=useState<TeacherRow[]>([]);const [school,setSchool]=useState<SchoolRow|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
  const [drawer,setDrawer]=useState(false);const [tab,setTab]=useState("All Teachers");const [search,setSearch]=useState("");const [favorites,setFavorites]=useState<string[]>([]);const [basic,setBasic]=useState<Record<string,string>>({});const [advanced,setAdvanced]=useState<Record<string,string>>({});const {showToast}=useToast();
  useEffect(()=>{setFavorites(readTeacherIds(SAVED_TEACHERS_KEY))},[]);
  useEffect(()=>{let active=true;(async()=>{try{const supabase=getSupabaseClient();const [teacherResult,schoolResult]=await Promise.all([supabase.from("teachers").select("*"),supabase.from("schools").select("*").eq("id",DEMO_SCHOOL_ID).single()]);if(teacherResult.error)throw teacherResult.error;if(schoolResult.error)throw schoolResult.error;if(active){setRows((teacherResult.data??[]) as TeacherRow[]);setSchool(schoolResult.data as SchoolRow)}}catch(cause){if(active)setError(cause instanceof Error?cause.message:"Unable to load discovery data.");}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
  const teachers=useMemo<Teacher[]>(()=>rows.map((row,index)=>{const scored=scoreTeacher(row,school);return {...row,name:row.full_name||"Teacher",match:scored.score,years:row.years_experience??0,languageDisplay:(row.languages??[]).join(", "),ageDisplay:(row.age_groups??[]).join(", "),certificateDisplay:(row.certificates??[]).join(", "),tone:tones[index%tones.length],imageUrl:row.profile_image_url||"",reasons:scored.reasons}}),[rows,school]);
  const basicOptions=useMemo(()=>({Subject:unique(teachers.map(t=>t.subject||"")),City:unique(teachers.map(t=>t.city||"")),Experience:["0–3 years","4–7 years","8+ years"],"Age Group":unique(teachers.flatMap(t=>t.age_groups??[])),Language:unique(teachers.flatMap(t=>(t.languages??[]).map(languageName)))}),[teachers]);
  const advancedOptions=useMemo<Record<string,string[]>>(()=>({Gender:[],Nationality:unique(teachers.map(t=>t.nationality||"")),Age:["20–29","30–39","40–49","50+"],Education:["Bachelor's","Master's","Doctorate"],Certificates:unique(teachers.flatMap(t=>t.certificates??[])),"School Type Experience":unique(teachers.flatMap(t=>t.school_type_experience??[])),Availability:unique(teachers.flatMap(t=>t.availability??[])),"Work Permit":unique(teachers.map(t=>t.work_permit||"")),"Willing to Relocate":["Yes","No"],"Employment Type":unique(teachers.flatMap(t=>t.employment_type??[])),"Teaching Mode":unique(teachers.flatMap(t=>t.teaching_mode??[])),"Has Video":["Yes","No"],"Has CV":["Yes","No"]}),[teachers]);
  const advancedCount=Object.values(advanced).filter(value=>value&&value!=="Any").length;
  const recommended=useMemo(()=>[...teachers].sort((a,b)=>b.match-a.match||b.years-a.years).slice(0,3),[teachers]);
  const recommendedIds=useMemo(()=>new Set(recommended.map(teacher=>teacher.id)),[recommended]);
  const results=useMemo(()=>teachers.filter(teacher=>{
    const query=search.trim().toLowerCase();const searchable=[teacher.full_name,teacher.subject,teacher.city,teacher.nationality,...(teacher.languages??[]),...(teacher.certificates??[])].filter(Boolean).join(" ").toLowerCase();
    if(query&&!searchable.includes(query))return false;if(tab==="Saved Teachers"&&!favorites.includes(teacher.id))return false;if(tab==="Recommended"&&!recommendedIds.has(teacher.id))return false;
    if(basic.Subject&&teacher.subject!==basic.Subject)return false;if(basic.City&&teacher.city!==basic.City)return false;if(basic["Age Group"]&&!(teacher.age_groups??[]).includes(basic["Age Group"]))return false;if(basic.Language&&!(teacher.languages??[]).some(item=>normalized(languageName(item))===normalized(basic.Language)))return false;
    if(basic.Experience){const years=teacher.years;if(basic.Experience==="0–3 years"&&years>3)return false;if(basic.Experience==="4–7 years"&&(years<4||years>7))return false;if(basic.Experience==="8+ years"&&years<8)return false}
    return matchesAdvanced(teacher,advanced);
  }),[advanced,basic,favorites,recommendedIds,search,tab,teachers]);
  const favorite=(id:string)=>setFavorites(toggleTeacherId(SAVED_TEACHERS_KEY,id));const clear=()=>{setSearch("");setBasic({});setAdvanced({});setTab("All Teachers")};const topReasons=unique(recommended.flatMap(teacher=>teacher.reasons)).slice(0,5);
  return <DashboardShell nav={schoolNav} role="School" initials="MI" hideBottomSettings>
    <header className="discover-heading"><h1>Discover Teachers</h1><p>Browse matching teachers and save your favourites.</p></header>
    <section className="recommendation-layout"><div className="recommendation-carousel"><div className="discover-section-title"><Sparkles/><h2>Recommended for You</h2></div><button className="carousel-arrow left" aria-label="Previous recommendations"><ArrowLeft/></button><div className="recommended-row">{recommended.map((teacher,index)=><TeacherCard key={teacher.id} teacher={teacher} compact favorite={favorites.includes(teacher.id)} onFavorite={()=>favorite(teacher.id)} imageIndex={index}/>)}</div><button className="carousel-arrow right" aria-label="Next recommendations"><ArrowRight/></button><div className="carousel-dots"><i className="active"/><i/><i/></div></div><aside className="recommendation-reason"><span><Target/></span><h2>Why these teachers?</h2><p>{topReasons.length?topReasons.join(". ")+".":"Recommendations use compatible school and teacher profile fields."}</p><Image src="/stationary-cup.png" width={95} height={80} alt=""/></aside></section>
    <nav className="teacher-tabs" aria-label="Teacher lists">{[{label:"All Teachers",icon:UsersRound},{label:"Recommended",icon:Star},{label:"Saved Teachers",icon:Heart}].map(({label,icon:Icon})=><button key={label} className={tab===label?"active":""} onClick={()=>setTab(label)}><Icon size={16}/>{label}</button>)}</nav>
    <div className="teacher-filter-row"><label className="teacher-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search teachers by name, subject, city..."/></label>{Object.entries(basicOptions).map(([label,options])=><label className="quick-filter quick-filter-control" key={label}><select aria-label={label} value={basic[label]||""} onChange={event=>setBasic(current=>({...current,[label]:event.target.value}))}><option value="">{label}</option>{options.map(option=><option key={option}>{option}</option>)}</select><ChevronDown/></label>)}<button className="quick-filter" disabled title="Profile completion is not stored in the teachers table">Profile Completion<ChevronDown/></button><button className={`advanced-trigger ${advancedCount?"active":""}`} onClick={()=>setDrawer(true)}><SlidersHorizontal/> Advanced Search{advancedCount?` (${advancedCount})`:""}</button><button className="clear-teacher-filters" onClick={clear}><RotateCcw/> Clear Filters</button></div>
    <section className="all-teachers-section"><div className="results-heading"><h2>{tab}</h2><span>{loading?"Loading teachers...":error?`Unable to load teachers: ${error}`:`${results.length} teachers found`}</span></div>{!loading&&!error&&(results.length?<div className="all-teacher-grid">{results.map((teacher,index)=><TeacherCard key={teacher.id} teacher={teacher} favorite={favorites.includes(teacher.id)} onFavorite={()=>favorite(teacher.id)} imageIndex={index+2}/>)}</div>:<div className="collection-empty"><span><Search/></span><h2>No teachers match these filters</h2><p>Clear or adjust your search and filters to see more teachers.</p><button className="empty-clear" onClick={clear}>Clear Filters</button></div>)}</section>
    {drawer&&<><button className="advanced-overlay" aria-label="Close advanced search" onClick={()=>setDrawer(false)}/><aside className="advanced-drawer"><header><div><span>Teacher filters</span><h2>Advanced Search</h2></div><button onClick={()=>setDrawer(false)} aria-label="Close"><X/></button></header><div className="advanced-content">{advancedGroups.map(group=><section key={group.title}><h3>{group.title}</h3>{group.fields.map(label=>{const disabled=label==="Gender";return <label key={label}><span>{label}</span><select disabled={disabled} title={disabled?"Gender is not stored in the teachers table":undefined} value={advanced[label]||"Any"} onChange={event=>setAdvanced(current=>({...current,[label]:event.target.value}))}><option>Any</option>{advancedOptions[label].map(option=><option key={option}>{option}</option>)}</select></label>})}</section>)}</div><footer><button onClick={()=>setAdvanced({})}>Clear Filters</button><button onClick={()=>{setDrawer(false);showToast(`${advancedCount} advanced filter${advancedCount===1?"":"s"} applied.`)}}>Apply Filters</button></footer></aside></>}
  </DashboardShell>
}

function matchesAdvanced(teacher:Teacher,filters:Record<string,string>){const selected=(key:string)=>filters[key]&&filters[key]!=="Any"?filters[key]:"";if(selected("Nationality")&&teacher.nationality!==selected("Nationality"))return false;if(selected("Age")){const age=teacher.age??0;const range=selected("Age");if(range==="20–29"&&(age<20||age>29))return false;if(range==="30–39"&&(age<30||age>39))return false;if(range==="40–49"&&(age<40||age>49))return false;if(range==="50+"&&age<50)return false}if(selected("Education")){const education=normalized(teacher.education);const level=selected("Education");if(level==="Bachelor's"&&!/\b(ba|bs|bsc|bachelor)/.test(education))return false;if(level==="Master's"&&!/\b(ma|ms|msc|master)/.test(education))return false;if(level==="Doctorate"&&!/\b(phd|doctor)/.test(education))return false}const arrays:[[string,string[]|null]]|[string,string[]|null][]=[["Certificates",teacher.certificates],["School Type Experience",teacher.school_type_experience],["Availability",teacher.availability],["Employment Type",teacher.employment_type],["Teaching Mode",teacher.teaching_mode]];for(const [key,values] of arrays)if(selected(key)&&!(values??[]).includes(selected(key)))return false;if(selected("Work Permit")&&teacher.work_permit!==selected("Work Permit"))return false;if(selected("Willing to Relocate")&&teacher.willing_to_relocate!==(selected("Willing to Relocate")==="Yes"))return false;if(selected("Has Video")&&teacher.has_video!==(selected("Has Video")==="Yes"))return false;if(selected("Has CV")&&teacher.has_cv!==(selected("Has CV")==="Yes"))return false;return true}
function TeacherCard({teacher,compact=false,favorite,onFavorite,imageIndex}:{teacher:Teacher;compact?:boolean;favorite:boolean;onFavorite:()=>void;imageIndex:number}){return <article data-index={imageIndex} className={`discover-teacher-card ${compact?"compact":""}`}><div className="discover-card-top"><span className={`discover-avatar ${teacher.tone}`}><Image src={teacher.imageUrl||"/Avatar%20.png"} width={72} height={72} unoptimized alt={`${teacher.name} portrait`}/></span><div><h3>{teacher.name}</h3><strong>{teacher.subject||"Subject not provided"}</strong><span><MapPin/> {teacher.city||"Location not provided"}</span></div><span className="discover-match">{teacher.match}%</span><button className={`discover-heart ${favorite?"saved":""}`} onClick={onFavorite} aria-label={`${favorite?"Remove":"Add"} ${teacher.name} ${favorite?"from":"to"} favourites`}><Heart fill={favorite?"currentColor":"none"}/></button></div><div className="teacher-compact-facts"><span><Clock3/> {teacher.years} years experience</span><span><Languages/> {teacher.languageDisplay||"Languages not provided"}</span><span><UsersRound/> {teacher.ageDisplay||"Age groups not provided"}</span></div><div className="discover-card-footer"><span><Award/> {teacher.certificateDisplay||"No certificate listed"}</span><Link href={`/school/teachers/${teacher.id}`}>View Profile</Link></div></article>}
