"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bookmark, Building2, Check, Eye, GraduationCap, Languages, LockKeyhole, MapPin, Search, ShieldCheck, Sparkles, Target, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { DashboardShell } from "@/components/dashboard-shell";
import { schoolNav } from "@/components/school-nav";
import { useToast } from "@/components/toast";
import { CONNECTION_REQUESTS_KEY, readTeacherIds, SAVED_TEACHERS_KEY, toggleTeacherId } from "@/components/school-teacher-state";
import { getSupabaseClient } from "@/lib/supabase";
import { useI18n } from "@/components/i18n";

type SchoolRow=Record<string,unknown>;
type Teacher={id:string;full_name:string|null;subject:string|null;city:string|null;years_experience:number|null;languages:string[]|null;age_groups:string[]|null;certificates:string[]|null;match_percentage:number|null;profile_image_url:string|null};
const text=(row:SchoolRow|null,...keys:string[])=>{for(const key of keys){const value=row?.[key];if(typeof value==="string"&&value)return value}return ""};
const values=(row:SchoolRow|null,...keys:string[])=>{for(const key of keys){const value=row?.[key];if(Array.isArray(value))return value.map(String);if(typeof value==="string"&&value)return value.split(/[|,]/).map(item=>item.trim()).filter(Boolean)}return []};

export default function SchoolDashboard(){
  const [school,setSchool]=useState<SchoolRow|null>(null);const [teachers,setTeachers]=useState<Teacher[]>([]);const [teacherCount,setTeacherCount]=useState(0);const [savedIds,setSavedIds]=useState<string[]>([]);const [unlockedIds,setUnlockedIds]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const {showToast}=useToast();
  const {t}=useI18n();
  useEffect(()=>{setSavedIds(readTeacherIds(SAVED_TEACHERS_KEY));setUnlockedIds(readTeacherIds(CONNECTION_REQUESTS_KEY));let active=true;(async()=>{const supabase=getSupabaseClient();const [schoolResult,teacherResult,countResult]=await Promise.all([supabase.from("schools").select("*").ilike("name","Marmara International College").limit(1).maybeSingle(),supabase.from("teachers").select("*").order("match_percentage",{ascending:false}).limit(3),supabase.from("teachers").select("id",{count:"exact",head:true})]);if(!active)return;if(schoolResult.error)setError(`School data: ${schoolResult.error.message}`);else setSchool(schoolResult.data as SchoolRow|null);if(teacherResult.error)setError(current=>current||`Teacher data: ${teacherResult.error.message}`);else setTeachers((teacherResult.data??[]) as Teacher[]);if(!countResult.error)setTeacherCount(countResult.count??0);setLoading(false)})();return()=>{active=false}},[]);
  const schoolName=text(school,"name","school_name")||"Marmara International College";const schoolType=text(school,"school_type","type")||"School profile";const ages=values(school,"student_age_groups","age_groups","ages");const languages=values(school,"languages_of_instruction","languages");const departments=values(school,"subjects","departments");
  const stats=useMemo(()=>[{label:"Recommended Teachers",value:String(teacherCount),note:"Available in the live directory",icon:Sparkles,tone:"green"},{label:"Recently Viewed Teachers",value:"—",note:"Tracking is not connected yet",icon:Eye,tone:"blue"},{label:"Contacts Unlocked",value:String(unlockedIds.length),note:"Available in your contacts",icon:LockKeyhole,tone:"ochre"},{label:"Saved Teachers",value:String(savedIds.length),note:"Ready to review",icon:Bookmark,tone:"sage"}],[savedIds.length,teacherCount,unlockedIds.length]);
  const save=(teacher:Teacher)=>{const next=toggleTeacherId(SAVED_TEACHERS_KEY,teacher.id);setSavedIds(next);showToast(`${teacher.full_name||"Teacher"} ${t(next.includes(teacher.id)?"saved for review.":"removed from saved teachers.")}`)};
  return <DashboardShell nav={schoolNav} role="School" initials="MI" hideBottomSettings>
    <header className="school-welcome"><div><span className="school-kicker">{t("School dashboard")}</span><h1>{t("Welcome back")}, {schoolName}</h1><p>{t("Discover matching teachers and manage your profile from one place.")}</p></div><span className="school-date">{t("School workspace")}</span></header>
    {error&&<div className="school-data-error">{error}. The `schools` table must allow anonymous read access for this prototype.</div>}
    <section className="school-hero"><div className="school-hero-copy"><span><Sparkles/> {t("Teacher discovery")}</span><h2>{t("Find the right teachers for your school")}</h2><p>{t("Explore compatible educators based on your school type, curriculum, student ages, languages of instruction, and location.")}</p><div><Link href="/school/teachers" className="school-primary">{t("Browse Teachers")} <ArrowRight/></Link><Link className="school-secondary" href="/school/profile/view">{t("View Profile")}</Link></div></div><div className="school-hero-art"><span/><Image src="/school-building.png" width={285} height={205} alt="" priority/></div></section>
    <section className="school-stat-grid" aria-label={t("School account statistics")}>{stats.map(({label,value,note,icon:Icon,tone})=><article key={label}><span className={`school-stat-icon ${tone}`}><Icon/></span><div><strong>{loading?"…":value}</strong><h2>{t(label)}</h2><p>{t(note)}</p></div></article>)}</section>
    <div className="school-main-grid"><section className="school-recommendations" id="teachers"><div className="school-section-head"><div><span className="school-kicker">{t("Curated for")} {schoolName}</span><h2>{t("Recommended Teachers")}</h2><p>{t("Highest matches from the live teacher directory.")}</p></div><Link href="/school/teachers">{t("View all teachers")} <ArrowRight/></Link></div><div className="school-teacher-grid">{teachers.map((teacher,index)=><TeacherCard teacher={teacher} index={index} saved={savedIds.includes(teacher.id)} onSave={()=>save(teacher)} key={teacher.id}/>)}</div></section>
      <aside className="school-right-rail"><section className="school-side-card why-card"><span className="side-card-icon"><Target/></span><h2>{t("Why these teachers?")}</h2><p>{t("Recommendations use the information in your school profile:")}</p><ul><li><Building2/> {schoolType}</li><li><UsersRound/> {ages.join(", ")||t("Student age groups")}</li><li><Languages/> {languages.join(", ")||t("Languages of instruction")}</li><li><GraduationCap/> {departments.join(", ")||t("Subject alignment")}</li><li><ShieldCheck/> {t("Profile details")}</li></ul><small>{t("Rule-based prototype recommendations")}</small></section>
        <section className="school-side-card quick-card"><h2>{t("Quick Actions")}</h2><nav><Link href="/school/teachers"><Search/> {t("Browse all teachers")} <ArrowRight/></Link><Link href="/school/profile"><Building2/> {t("Update school profile")} <ArrowRight/></Link><Link href="/school/saved-teachers"><Bookmark/> {t("Review saved teachers")} <ArrowRight/></Link><Link href="/school/unlocked-teachers"><LockKeyhole/> {t("View unlocked contacts")} <ArrowRight/></Link></nav></section>
        <section className="school-side-card recent-card"><div className="rail-title"><h2>{t("Top Matches")}</h2><Link href="/school/teachers">{t("See all")}</Link></div>{teachers.map(teacher=><Link href={`/school/teachers/${teacher.id}`} className="recent-teacher" key={teacher.id}><Portrait teacher={teacher}/><div><strong>{teacher.full_name||"Teacher"}</strong><span>{teacher.subject||t("Subject not provided")}</span><small><MapPin/> {teacher.city||t("Location not provided")} · {teacher.match_percentage??0}% {t("match")}</small></div></Link>)}</section></aside>
    </div>
  </DashboardShell>
}

function TeacherCard({teacher,saved,onSave}:{teacher:Teacher;index:number;saved:boolean;onSave:()=>void}){const {t}=useI18n();const reasons=[teacher.subject,(teacher.age_groups??[])[0],(teacher.languages??[])[0],(teacher.certificates??[])[0]].filter((value):value is string=>Boolean(value));return <article className="school-teacher-card"><div className="teacher-cover"><span className="match-badge"><Sparkles/> {teacher.match_percentage??0}% {t("match")}</span><button className="teacher-save" aria-label={`${t(saved?"Remove":"Save")} ${teacher.full_name||"teacher"}`} onClick={onSave}><Bookmark fill={saved?"currentColor":"none"}/></button><Portrait teacher={teacher}/></div><div className="teacher-card-body"><h3>{teacher.full_name||"Teacher"}</h3><strong className="teacher-subject">{teacher.subject||t("Subject not provided")}</strong><span className="teacher-location"><MapPin/> {teacher.city||t("Location not provided")}</span><div className="match-reasons"><h4>{t("Why this teacher matches")}</h4>{reasons.map(reason=><span key={reason}><Check/>{reason}</span>)}</div><dl><div><dt>{t("Experience")}</dt><dd>{teacher.years_experience??0} {t("years")}</dd></div><div><dt>{t("Languages")}</dt><dd>{(teacher.languages??[]).join(", ")||t("Not provided")}</dd></div><div><dt>{t("Age groups")}</dt><dd>{(teacher.age_groups??[]).join(", ")||t("Not provided")}</dd></div><div><dt>{t("Certificates")}</dt><dd>{(teacher.certificates??[]).join(", ")||t("Not provided")}</dd></div></dl><div className="teacher-actions"><Link href={`/school/teachers/${teacher.id}`}>{t("View Profile")}</Link><Link href={`/school/teachers/${teacher.id}`}><LockKeyhole/> {t("Request to Connect")}</Link></div></div></article>}
function Portrait({teacher}:{teacher:Teacher}){return <span className="school-portrait mint"><Image src={teacher.profile_image_url||"/Avatar%20.png"} width={82} height={82} unoptimized alt={`${teacher.full_name||"Teacher"} portrait`}/></span>}
