"use client";

import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bookmark, Building2, Check, Eye, GraduationCap, Languages, LockKeyhole, MapPin, Search, ShieldCheck, Sparkles, Target, UsersRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { DashboardShell } from "@/components/dashboard-shell";
import { schoolNav } from "@/components/school-nav";
import { useToast } from "@/components/toast";
import { CONNECTION_REQUESTS_KEY, readTeacherIds, SAVED_TEACHERS_KEY, toggleTeacherId } from "@/components/school-teacher-state";
import { getSupabaseClient } from "@/lib/supabase";

type SchoolRow=Record<string,unknown>;
type Teacher={id:string;full_name:string|null;subject:string|null;city:string|null;years_experience:number|null;languages:string[]|null;age_groups:string[]|null;certificates:string[]|null;match_percentage:number|null;profile_image_url:string|null};
const text=(row:SchoolRow|null,...keys:string[])=>{for(const key of keys){const value=row?.[key];if(typeof value==="string"&&value)return value}return ""};
const values=(row:SchoolRow|null,...keys:string[])=>{for(const key of keys){const value=row?.[key];if(Array.isArray(value))return value.map(String);if(typeof value==="string"&&value)return value.split(/[|,]/).map(item=>item.trim()).filter(Boolean)}return []};

export default function SchoolDashboard(){
  const [school,setSchool]=useState<SchoolRow|null>(null);const [teachers,setTeachers]=useState<Teacher[]>([]);const [teacherCount,setTeacherCount]=useState(0);const [savedIds,setSavedIds]=useState<string[]>([]);const [unlockedIds,setUnlockedIds]=useState<string[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const {showToast}=useToast();
  useEffect(()=>{setSavedIds(readTeacherIds(SAVED_TEACHERS_KEY));setUnlockedIds(readTeacherIds(CONNECTION_REQUESTS_KEY));let active=true;(async()=>{const supabase=getSupabaseClient();const [schoolResult,teacherResult,countResult]=await Promise.all([supabase.from("schools").select("*").ilike("name","Marmara International College").limit(1).maybeSingle(),supabase.from("teachers").select("*").order("match_percentage",{ascending:false}).limit(3),supabase.from("teachers").select("id",{count:"exact",head:true})]);if(!active)return;if(schoolResult.error)setError(`School data: ${schoolResult.error.message}`);else setSchool(schoolResult.data as SchoolRow|null);if(teacherResult.error)setError(current=>current||`Teacher data: ${teacherResult.error.message}`);else setTeachers((teacherResult.data??[]) as Teacher[]);if(!countResult.error)setTeacherCount(countResult.count??0);setLoading(false)})();return()=>{active=false}},[]);
  const schoolName=text(school,"name","school_name")||"Marmara International College";const schoolType=text(school,"school_type","type")||"School profile";const ages=values(school,"student_age_groups","age_groups","ages");const languages=values(school,"languages_of_instruction","languages");const departments=values(school,"subjects","departments");
  const stats=useMemo(()=>[{label:"Recommended Teachers",value:String(teacherCount),note:"Available in the live directory",icon:Sparkles,tone:"green"},{label:"Recently Viewed Teachers",value:"—",note:"Tracking is not connected yet",icon:Eye,tone:"blue"},{label:"Contacts Unlocked",value:String(unlockedIds.length),note:"Available in your contacts",icon:LockKeyhole,tone:"ochre"},{label:"Saved Teachers",value:String(savedIds.length),note:"Ready to review",icon:Bookmark,tone:"sage"}],[savedIds.length,teacherCount,unlockedIds.length]);
  const save=(teacher:Teacher)=>{const next=toggleTeacherId(SAVED_TEACHERS_KEY,teacher.id);setSavedIds(next);showToast(next.includes(teacher.id)?`${teacher.full_name||"Teacher"} saved for review.`:`${teacher.full_name||"Teacher"} removed from saved teachers.`)};
  return <DashboardShell nav={schoolNav} role="School" initials="MI" hideBottomSettings>
    <header className="school-welcome"><div><span className="school-kicker">School dashboard</span><h1>Welcome back, {schoolName}</h1><p>Discover matching teachers and manage your profile from one place.</p></div><span className="school-date">School workspace</span></header>
    {error&&<div className="school-data-error">{error}. The `schools` table must allow anonymous read access for this prototype.</div>}
    <section className="school-hero"><div className="school-hero-copy"><span><Sparkles/> Teacher discovery</span><h2>Find the right teachers for your school</h2><p>Explore compatible educators based on your school type, curriculum, student ages, languages of instruction, and location.</p><div><Link href="/school/teachers" className="school-primary">Browse Teachers <ArrowRight/></Link><Link className="school-secondary" href="/school/profile/view">View Profile</Link></div></div><div className="school-hero-art"><span/><Image src="/school-building.png" width={285} height={205} alt="School campus illustration" priority/></div></section>
    <section className="school-stat-grid" aria-label="School account statistics">{stats.map(({label,value,note,icon:Icon,tone})=><article key={label}><span className={`school-stat-icon ${tone}`}><Icon/></span><div><strong>{loading?"…":value}</strong><h2>{label}</h2><p>{note}</p></div></article>)}</section>
    <div className="school-main-grid"><section className="school-recommendations" id="teachers"><div className="school-section-head"><div><span className="school-kicker">Curated for {schoolName}</span><h2>Recommended Teachers</h2><p>Highest matches from the live teacher directory.</p></div><Link href="/school/teachers">View all teachers <ArrowRight/></Link></div><div className="school-teacher-grid">{teachers.map((teacher,index)=><TeacherCard teacher={teacher} index={index} saved={savedIds.includes(teacher.id)} onSave={()=>save(teacher)} key={teacher.id}/>)}</div></section>
      <aside className="school-right-rail"><section className="school-side-card why-card"><span className="side-card-icon"><Target/></span><h2>Why these teachers?</h2><p>Recommendations use the information in your school profile:</p><ul><li><Building2/> {schoolType}</li><li><UsersRound/> {ages.join(", ")||"Student age groups"}</li><li><Languages/> {languages.join(", ")||"Languages of instruction"}</li><li><GraduationCap/> {departments.join(", ")||"Subject alignment"}</li><li><ShieldCheck/> Profile details</li></ul><small>Rule-based prototype recommendations</small></section>
        <section className="school-side-card quick-card"><h2>Quick Actions</h2><nav><Link href="/school/teachers"><Search/> Browse all teachers <ArrowRight/></Link><Link href="/school/profile"><Building2/> Update school profile <ArrowRight/></Link><Link href="/school/saved-teachers"><Bookmark/> Review saved teachers <ArrowRight/></Link><Link href="/school/unlocked-teachers"><LockKeyhole/> View unlocked contacts <ArrowRight/></Link></nav></section>
        <section className="school-side-card recent-card"><div className="rail-title"><h2>Top Matches</h2><Link href="/school/teachers">See all</Link></div>{teachers.map(teacher=><Link href={`/school/teachers/${teacher.id}`} className="recent-teacher" key={teacher.id}><Portrait teacher={teacher}/><div><strong>{teacher.full_name||"Teacher"}</strong><span>{teacher.subject||"Subject not provided"}</span><small><MapPin/> {teacher.city||"Location not provided"} · {teacher.match_percentage??0}% match</small></div></Link>)}</section></aside>
    </div>
  </DashboardShell>
}

function TeacherCard({teacher,saved,onSave}:{teacher:Teacher;index:number;saved:boolean;onSave:()=>void}){const reasons=[teacher.subject,(teacher.age_groups??[])[0],(teacher.languages??[])[0],(teacher.certificates??[])[0]].filter((value):value is string=>Boolean(value));return <article className="school-teacher-card"><div className="teacher-cover"><span className="match-badge"><Sparkles/> {teacher.match_percentage??0}% match</span><button className="teacher-save" aria-label={`${saved?"Remove":"Save"} ${teacher.full_name||"teacher"}`} onClick={onSave}><Bookmark fill={saved?"currentColor":"none"}/></button><Portrait teacher={teacher}/></div><div className="teacher-card-body"><h3>{teacher.full_name||"Teacher"}</h3><strong className="teacher-subject">{teacher.subject||"Subject not provided"}</strong><span className="teacher-location"><MapPin/> {teacher.city||"Location not provided"}</span><div className="match-reasons"><h4>Why this teacher matches</h4>{reasons.map(reason=><span key={reason}><Check/>{reason}</span>)}</div><dl><div><dt>Experience</dt><dd>{teacher.years_experience??0} years</dd></div><div><dt>Languages</dt><dd>{(teacher.languages??[]).join(", ")||"Not provided"}</dd></div><div><dt>Age groups</dt><dd>{(teacher.age_groups??[]).join(", ")||"Not provided"}</dd></div><div><dt>Certificates</dt><dd>{(teacher.certificates??[]).join(", ")||"Not provided"}</dd></div></dl><div className="teacher-actions"><Link href={`/school/teachers/${teacher.id}`}>View Profile</Link><Link href={`/school/teachers/${teacher.id}`}><LockKeyhole/> Request to Connect</Link></div></div></article>}
function Portrait({teacher}:{teacher:Teacher}){return <span className="school-portrait mint"><Image src={teacher.profile_image_url||"/Avatar%20.png"} width={82} height={82} unoptimized alt={`${teacher.full_name||"Teacher"} portrait`}/></span>}
