"use client";
/* eslint-disable @next/next/no-img-element */

import Image from "next/image";
import Link from "next/link";
import { BookOpen, Building2, Check, Eye, GraduationCap, Mail, MapPin, Save, School, ShieldCheck, Upload, UsersRound } from "lucide-react";
import { useEffect, useState } from "react";
import { DashboardShell } from "@/components/dashboard-shell";
import { schoolNav } from "@/components/school-nav";
import { useToast } from "@/components/toast";
import { defaultSchoolProfile as defaults, SCHOOL_PROFILE_STORAGE as STORAGE, splitSchoolValues as split } from "@/components/school-profile-data";


export default function EditSchoolProfile(){
  const [form,setForm]=useState(defaults);const {showToast}=useToast();
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=localStorage.getItem(STORAGE);if(saved)setForm({...defaults,...JSON.parse(saved)})}catch{}},0);return()=>clearTimeout(timer)},[]);
  const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  const save=()=>{localStorage.setItem(STORAGE,JSON.stringify(form));showToast("School profile updated successfully.")};
  const logo=(file?:File)=>{if(!file)return;if(file.size>450000){showToast("Please choose a logo under 450 KB for this demo.");return}const reader=new FileReader();reader.onload=()=>{const next={...form,logo:String(reader.result)};setForm(next);localStorage.setItem(STORAGE,JSON.stringify(next));showToast("School logo updated successfully.")};reader.readAsDataURL(file)};
  return <DashboardShell nav={schoolNav} role="School" initials="AC" hideBottomSettings>
    <section className="school-profile-banner"><div className="school-logo-preview">{form.logo?<img src={form.logo} alt={`${form.name} logo`}/>:<Building2/>}</div><div className="school-banner-copy"><span className="school-kicker">Edit school profile</span><h1>{form.name||"School name"}</h1><p><MapPin/> {form.city||"Location"} <i/> <School/> {form.type||"School type"}</p><div>{split(form.ages).map(x=><span key={x}>{x}</span>)}{split(form.languages).map(x=><span key={x}>{x}</span>)}</div></div><Image src="/school-building.png" width={280} height={190} alt="" priority/><Link href="/school/profile/view" className="school-view-public"><Eye/> View Public Profile</Link></section>
    <div className="school-edit-layout"><aside className="school-edit-index"><span>Profile sections</span><a href="#logo">School logo</a><a href="#basic">Basic information</a><a href="#education">Students & education</a><a href="#details">School details</a><a href="#support">Teacher support</a><a href="#facilities">Facilities & highlights</a><a href="#contact">Contact information</a></aside>
      <form className="school-profile-form" onSubmit={e=>{e.preventDefault();save()}}>
        <FormCard id="logo" icon={Building2} title="School Logo" copy="Upload the mark schools and teachers will see across BULBENI."><div className="school-logo-editor"><div className="school-logo-preview small">{form.logo?<img src={form.logo} alt="Logo preview"/>:<Building2/>}</div><div><label className="school-upload-button"><Upload/> {form.logo?"Change Logo":"Upload Logo"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>logo(e.target.files?.[0])}/></label><p>PNG, JPG or WebP · Maximum 450 KB for this prototype</p>{form.logo&&<button type="button" onClick={()=>set("logo","")}>Remove logo</button>}</div></div></FormCard>
        <FormCard id="basic" icon={School} title="Basic Information" copy="Core information shown at the top of your public profile."><div className="school-form-grid"><Field label="School name" value={form.name} onChange={v=>set("name",v)}/><Select label="School type" value={form.type} onChange={v=>set("type",v)} options={["International School","Private School","Public School","IB World School","Language School"]}/><Field label="Location / city" value={form.city} onChange={v=>set("city",v)}/><Field label="Website" value={form.website} onChange={v=>set("website",v)}/><Field wide label="Full address" value={form.address} onChange={v=>set("address",v)}/><Field wide area label="About school" value={form.about} onChange={v=>set("about",v)}/></div></FormCard>
        <FormCard id="education" icon={GraduationCap} title="Students & Education" copy="Describe the learners, teaching languages, and academic structure."><Choice label="Student age groups" options={["Early Years","Primary School","Middle School","High School","Adult Learners"]} value={form.ages} onChange={v=>set("ages",v)}/><Choice label="Languages of instruction" options={["English","Romanian","French","German","Turkish","Spanish"]} value={form.languages} onChange={v=>set("languages",v)}/><Choice label="Subjects / Departments" options={["English & Humanities","Mathematics","Science & STEM","Languages","Arts & Music","Physical Education"]} value={form.departments} onChange={v=>set("departments",v)}/><div className="school-form-grid compact"><Field label="Curriculum" value={form.curriculum} onChange={v=>set("curriculum",v)}/><Select label="Schedule type" value={form.schedule} onChange={v=>set("schedule",v)} options={["Full day","Half day","Boarding","Flexible"]}/></div></FormCard>
        <FormCard id="details" icon={UsersRound} title="School Details" copy="Give teachers useful context about your school community."><div className="school-form-grid three"><Field label="Number of campuses" value={form.campuses} onChange={v=>set("campuses",v)}/><Field label="Approximate students" value={form.students} onChange={v=>set("students",v)}/><Field label="Years operating" value={form.years} onChange={v=>set("years",v)}/></div></FormCard>
        <FormCard id="support" icon={ShieldCheck} title="Teacher Support" copy="Explain the practical support available to prospective teachers."><div className="support-grid"><div><Select label="Work permit support" value={form.workPermit} onChange={v=>set("workPermit",v)} options={["Yes","No","Case-by-case"]}/><Field area label="Optional explanation" value={form.workPermitNote} onChange={v=>set("workPermitNote",v)}/></div><div><Select label="Accommodation support" value={form.accommodation} onChange={v=>set("accommodation",v)} options={["Yes","No","Assistance provided"]}/><Field area label="Optional explanation" value={form.accommodationNote} onChange={v=>set("accommodationNote",v)}/></div></div></FormCard>
        <FormCard id="facilities" icon={BookOpen} title="Facilities / Highlights" copy="Select the facilities and qualities that distinguish your campus."><Choice label="School highlights" options={["STEM / Science Labs","Library","Language Learning Labs","Sports Facilities","Art & Music Studios","Safe / Secure Campus"]} value={form.highlights} onChange={v=>set("highlights",v)}/><Field label="Add another highlight" value="" placeholder="Type a custom highlight" onChange={v=>{if(v)set("highlights",[...split(form.highlights),v].join("|"))}}/></FormCard>
        <FormCard id="contact" icon={Mail} title="Contact / Admin Information" copy="Administrative contact details used for the school profile."><div className="school-form-grid"><Field label="Contact email" value={form.email} onChange={v=>set("email",v)}/><Field label="Phone number" value={form.phone} onChange={v=>set("phone",v)}/><Field label="Website" value={form.website} onChange={v=>set("website",v)}/><Field label="Address" value={form.address} onChange={v=>set("address",v)}/></div></FormCard>
        <div className="school-form-actions"><Link href="/school">Cancel</Link><button type="submit"><Save/> Save Changes</button></div>
      </form>
    </div>
  </DashboardShell>
}

function FormCard({id,icon:Icon,title,copy,children}:{id:string;icon:React.ComponentType<{size?:number}>;title:string;copy:string;children:React.ReactNode}){return <section className="school-form-card" id={id}><header><span><Icon/></span><div><h2>{title}</h2><p>{copy}</p></div></header>{children}</section>}
function Field({label,value,onChange,placeholder,wide,area}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;wide?:boolean;area?:boolean}){return <label className={`school-field ${wide?"wide":""}`}><span>{label}</span>{area?<textarea value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} rows={4}/>:<input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>}</label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="school-field"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Choice({label,options,value,onChange}:{label:string;options:string[];value:string;onChange:(v:string)=>void}){const selected=split(value);return <fieldset className="school-choice"><legend>{label}</legend><div>{options.map(x=><button type="button" key={x} className={selected.includes(x)?"selected":""} onClick={()=>onChange(selected.includes(x)?selected.filter(y=>y!==x).join("|"):[...selected,x].join("|"))}>{selected.includes(x)&&<Check/>}{x}</button>)}</div></fieldset>}
